#!/bin/bash

. .gbt/gbt.properties

if [ -z $GBT_VERSION ]; then
    echo "GBT_VERSION is required in .gbt/gbt.properties"
    exit 1
fi

    echo "|$GBT_URL|"
if [ -z $GBT_URL ]; then
    echo "GBT_URL is required in .gbt/gbt.properties"
    exit 1
fi

echo "GBT $GBT_VERSION!"

GBT_VERSION_FOLDER="$HOME/.gbt/gbt/$GBT_VERSION"

mkdir -p "$GBT_VERSION_FOLDER"

GBT_BIN="$GBT_VERSION_FOLDER/gbt"

if [ ! -f "$GBT_BIN" ] || [ "$GBT_FORCE_DOWNLOAD" == "true" ]; then
    if [[ $GBT_URL == http* ]];
    then
        echo "Downloading $GBT_URL"
        wget "$GBT_URL" -O "$GBT_BIN"
    else
        echo "Copying $GBT_URL"
        cp "$GBT_URL" "$GBT_BIN"
    fi

    chmod +x "$GBT_BIN"
fi

"$GBT_BIN" "$@"
